### ISSUE TITLE
Flyout panel remains open when user navigates away from page.

### ISSUE THREAD

**Issue by kidchunks** [blackbaud/skyux-flyout#20]
### Expected behavior
When a user navigates from any page containing an active flyout panel, the active flyout panel should be closed.

### Actual behavior
Active flyout panel remains open.

### Steps to reproduce

1. https://developer.blackbaud.com/skyux2/
2. click "Components"
3. Scroll down and click "Flyout"
4. Open a flyout panel from the demo section
5. Click the "Components" link in the top navigation while the flyout panel remains open.

### Plunker (see example SKY UX 2 plunker template at: https://plnkr.co/edit/GeP22YbirEzceF3NVu39?p=preview)

N/A

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.0.1`
