### ISSUE TITLE
Flyout with infinity scroll Load more button closes flyout unexpectedly 

### ISSUE THREAD

**Issue by JaminQuimby** [blackbaud/skyux-flyout#26]
### Expected behavior
Flyout should load a new list.
### Actual behavior
Flyout closes unexpectedly
### Steps to reproduce
Create a Flyout, add a sky-list with a Load More button, click load more button, watch flyout close.
Also tested programmatic way to initiate a click, ```document.querySelectorAll('.sky-btn.sky-btn-default.ng-star-inserted')[0].click()``` the click is falling though to the flyout.
### Severity
High
### Impact
Clients cannot load a 2nd page on their list.

**Comment by Blackbaud-TrevorBurch** [comment]
This has also been found to happen when a vertical tabset is placed inside a flyout (of note is that you may need to shrink your screen to mobile size due to an unrelated responsiveness bug).
