### ISSUE TITLE
Flyout closes when resizing past browser window

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-flyout#29]
### Expected behavior
Flyout should not close when resizing.

### Actual behavior
If you click + drag the resize past the edge of the browser window, then release the button, the flyout closes.

It will also close if you click + drag larger than the flyout can go and then release the mouse click on the document body.

**Comment by Blackbaud-TrevorBurch** [comment]
This has been indirectly addressed in version `3.1.1`
