### ISSUE TITLE
Flyout should stop resizing when it is 20px less than the full screen size

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-flyout#35]
Per the UX guidelines the flyout should stop resizing when it is 20px less than the full window size. 

@Blackbaud-ToddRoberts could you verify if the flyout should then automatically shrink when the window is resized smaller and the same condition is met?

**Comment by Blackbaud-ToddRoberts** [comment]
Yes it should

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.1`
