### ISSUE TITLE
Flyout size should be remembered globally

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-flyout#38]
Per the UX guidelines we should remember the user's flyout size globally utilizing the UI config service.

**Comment by Blackbaud-SteveBrush** [comment]
Current UX Guidelines, "When users resize the panel, the system remembers their preferred size globally."
See: https://developer.blackbaud.com/skyux/components/flyout#ux-guidelines

**Comment by Blackbaud-ToddRoberts** [comment]
It should remember the size for that particular flyout, e.g. on a constituent list if they resize the flyout, leave, and come back and open the flyout for another constituent. It should not make all instances of flyout that size, e.g. if they resize a constituent flyout then go to a gift list, the gift flyout should have a separate width stored.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.0`
