### ISSUE TITLE
Modify full screen rule

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-flyout#39]
Per discussion with @Blackbaud-ToddRoberts we should remove the full screen being set on 768px and instead set this if (full screen width - 20px) is less than the `minWidth` set on the flyout (320px  or whatever the consumer specifies).

**Comment by Blackbaud-ToddRoberts** [comment]
We should make the described update, and trigger full screen mode when viewport width - 20px < minWidth.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.1`
