### ISSUE TITLE
Hyperlinks do not work from within flyouts

### ISSUE THREAD

**Issue by Blackbaud-CodyProbst** [blackbaud/skyux-flyout#43]
### Expected behavior

When clicking hyperlinks inside a flyout, that are not the permalink in the flyout header, the browser navigates to the linked page.

### Actual behavior

When clicking hyperlinks no browser navigation happens. There are no console errors from these click events. This is happening in versions back to at least 3.0.3

### Steps to reproduce

1. Go to the skyux flyout demo page https://developer.blackbaud.com/skyux/components/flyout
2. Open any of the demo flyouts
3. Click on the hyperlink for "lists"
4. Navigation does not happen.

**Comment by Blackbaud-AlexKingman** [comment]
Most likely the culprit:
https://github.com/blackbaud/skyux-flyout/pull/30/files#diff-977138d6d19050f326a34571f1b65833R163

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.1`
