### ISSUE TITLE
Angular 7 compatibility issues

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux-flyout#55]
There are two different issues found when attempting to use the library with a clean Angular 7 setup.

1. The animation modules is not imported and thus the animations fail to fire when opening/closing a flyout
2. The merge Observable operator is no longer imported by RxJs 6 and thus causes an error when the library attempts to initialize.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.1`
