### ISSUE TITLE
No padding between buttons in customized header.

### ISSUE THREAD

**Issue by kidchunks** [blackbaud/skyux-flyout#63]
### Expected behavior
When you open a fly-out panel with a customized header. The buttons should have padding between them (Iterators, close button and view record, etc).

### Actual behavior
When you open a fly-out panel with a customized header. The buttons should do not padding between them.

### Steps to reproduce
1. Visit [here](https://developer.blackbaud.com/skyux/components/flyout) to visit the SKYUX fly-out component page.
2. Scroll down to the section labelled '**Demo**'.
3. Click on any of the buttons under the header '**Flyout with customized headers**'.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.3`
