### ISSUE TITLE
Switching Flyouts Requires Multiple Clicks

### ISSUE THREAD

**Issue by Blackbaud-VanesaiXiong** [blackbaud/skyux-flyout#81]
### Expected behavior
Clicking on an element to open a flyout, with another flyout already open, should close the current flyout and open the new flyout.

### Actual behavior
The current flyout closes, but no new flyout opens (until clicking on the element a second time).

### Steps to reproduce
1. Locate a page with multiple elements (at least 2) that open a flyout.
2. Click on the first element
    1. Flyout for the first element opens
3. Click on the second element
    1. Flyout closes
    2. New flyout...
        1. Expected - opens
        2. Actual - does _not_ open

### Severity
Low

### Impact
Medium

[AB#1578310](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1578310)

**Comment by Blackbaud-VanesaiXiong** [comment]
It was working (per the expected behavior) on version 3.2.4.

**Comment by Blackbaud-SteveBrush** [comment]
Do you mind verifying that version `3.2.4` works by running `skyux install`? We checked the changes between `3.2.4` and `3.3.0` and nothing jumped out as a potential culprit.
https://github.com/blackbaud/skyux-flyout/compare/3.2.4...3.3.0

**Comment by Blackbaud-VanesaiXiong** [comment]
Sorry, I have my GitHub emails filtered into a folder I don't check very often.

We actually have the flyout set up across two different SPAs. When I was testing it previously, I was updating/downgrading both SPAs at the same time. I'll try them separately and report back the results, in case that's a factor.

**Comment by Blackbaud-VanesaiXiong** [comment]
We have 2 SPAs (main spa, and an addin spa that houses all the flyouts+addins) and I'm getting really inconsistent results among both versions of the flyout. At first I thought it was because of where the flyout was getting invoked (tile, split-view, etc), but even then it's a mixed bag (often multiple clicks but sometimes one). I'll draw out the scenarios tomorrow.

**Comment by Blackbaud-VanesaiXiong** [comment]
|Main SPA|Addin SPA|Invoked From|Result|
|-|-|-|-|
|3.3.0|3.3.0|<ul><li>Calendar Month/Week/Day View</li><li>Calendar List View</li><li>SplitView Content</li><li>Addin Tile<sup>1</sup></li></ul>|<ul><li>20/80 single/multiple</li><li>Multiple clicks</li><li>50/50 single/multiple</li><li>Single click</li></ul>|
|3.3.0|3.2.4|<ul><li>Calendar Month/Week/Day View</li><li>Calendar List View</li><li>SplitView Content</li><li>Addin Tile<sup>1</sup></li></ul>|<ul><li>20/80 single/multiple</li><li>Multiple clicks</li><li>50/50 single/multiple</li><li>Single click</li></ul>|
|3.2.4|3.3.0|<ul><li>Calendar Month/Week/Day View</li><li>Calendar List View</li><li>SplitView Content</li><li>Addin Tile<sup>1</sup></li></ul>|<ul><li>20/80 single/multiple</li><li>Multiple clicks</li><li>50/50 single/multiple</li><li>Single click</li></ul>|
|3.2.4|3.2.4|<ul><li>Calendar Month/Week/Day View</li><li>Calendar List View</li><li>SplitView Content</li><li>Addin Tile<sup>1</sup></li></ul>|<ul><li>80/20 single/multiple</li><li>Multiple clicks</li><li>80/20 single/multiple</li><li>Single click</li></ul>|

<sub>1 - Flyout switching invoked from an addin switches the content without closing and re-opening the flyout.<sub>

**Comment by Blackbaud-VanesaiXiong** [comment]
[Link to demo video](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1590771500291500?thread_ts=1589575009.149500&cid=C3TQ4C0KG), showing the inconsistent click behavior.

**Comment by Blackbaud-KrisMahon** [comment]
We are upgrading a SPA to SKYUX 4 and are running into the same usability issue.  Previously on 3.2.3, we could just click on different rows in our list and the flyout would say open and load the page for each row - a nice seemless experience for the user.  Now on 4.0.0, when clicking a different row it just closes the flyout which forces the user to click the row a second time to open the flyout.  This is will be a big usability concern for customers.

**Comment by Blackbaud-KrisMahon** [comment]
Looking through the commit history, it seems like the problem may be related to this change, but I don't know for sure.  It is just the only commit after 3.2.3 that seems to have modified the code in a way that looks related.

https://github.com/blackbaud/skyux-flyout/commit/4ef1545003ab700ff1e372bfeb52c14846aa5ec7#diff-3139f689c3958959162f5f01c2cf5205

**Comment by Blackbaud-TrevorBurch** [comment]
In `skyux/flyout` version `4.0.2`
